# <font color = dodgerred>**HW1 - 15 Points** </font>
- **You have to submit two files for this part of the HW**
  >(1) ipynb (colab notebook) and<br>
  >(2) pdf file (pdf version of the colab file).**
- **Files should be named as follows**:
>FirstName_LastName_HW_1**


In [38]:
import torch
import time

# <font color = dodgerred>**Q1 : Create Tensor (1/2 Point)**
 Create a torch Tensor of shape (5, 3) which is filled with zeros. Modify the tensor to set element (0, 2) to 10 and element (2, 0)  to 100.

In [39]:
my_tensor = torch.zeros(5, 3)

In [40]:
my_tensor.shape

torch.Size([5, 3])

In [41]:
my_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [42]:
# Manually set the value at the first row and third column to 10,
# and the value at the third row and first column to 100 in the tensor named "my_tensor".

# CODE HERE
my_tensor[0, 2]=10
my_tensor[2, 0]=100

In [43]:
my_tensor

tensor([[  0.,   0.,  10.],
        [  0.,   0.,   0.],
        [100.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]])

# <font color = dodgerred>**Q2: Reshape tensor (1/2 Point)**
You have following tensor as input:

```x=torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])```

Using only reshaping functions (like view, reshape, transpose, permute), you need to get at the following tensor as output:

```
tensor([[ 0,  4,  8, 12, 16, 20],
        [ 1,  5,  9, 13, 17, 21],
        [ 2,  6, 10, 14, 18, 22],
        [ 3,  7, 11, 15, 19, 23]])
```



In [44]:
x=torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [45]:
x = x.reshape(6,4).T
x

tensor([[ 0,  4,  8, 12, 16, 20],
        [ 1,  5,  9, 13, 17, 21],
        [ 2,  6, 10, 14, 18, 22],
        [ 3,  7, 11, 15, 19, 23]])

# <font color = dodgerred>**Q3: Slice tensor (1Point)**

- Slice the tensor x to get the following
>- last row of x
>- fourth column of x
>- first three rows and first two columns - the shape of subtensor should be (3,2)
>- odd valued rows and columns

In [46]:
x = torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 8, 10], [11, 12, 13, 14, 15]])
x

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  8, 10],
        [11, 12, 13, 14, 15]])

In [47]:
x.shape

torch.Size([3, 5])

In [48]:
# Student Task: Retrieve the last row of the tensor 'x'
# Hint: Negative indexing can help you select rows or columns counting from the end of the tensor.
# Think about how you can select all columns for the desired row.
last_row = x[-1,:]
last_row

tensor([11, 12, 13, 14, 15])

In [49]:
# Student Task: Retrieve the fourth column of the tensor 'x'
# Hint: Pay attention to the indexing for both rows and columns.
# Remember that indexing in Python starts from zero.
fourth_column = x[:,3]
fourth_column

tensor([ 4,  8, 14])

In [50]:
# Student Task: Retrieve the first 3 rows and first 2 columns from the tensor 'x'.
# Hint: Use slicing to extract the required subset of rows and columns.
first_3_rows_2_columns = x[:3,:2]
first_3_rows_2_columns

tensor([[ 1,  2],
        [ 6,  7],
        [11, 12]])

In [51]:
# Student Task: Retrieve the rows and columns with odd-indexed positions from the tensor 'x'.
# Hint: Use stride slicing to extract the required subset of rows and columns with odd indices.
odd_valued_rows_columns = x[::2,::2]
odd_valued_rows_columns

tensor([[ 1,  3,  5],
        [11, 13, 15]])

#  <font color = dodgerred>**Q4 -Normalize Function (1/2 Points)**<font>

Write the function that normalizes the columns of a matrix. You have to compute the mean and standard deviation of each column. Then for each element of the column, you subtract the mean and divide by the standard deviation.

In [52]:
# Given Data
x = [[ 3,  60,  100, -100],
     [ 2,  20,  600, -600],
     [-5,  50,  900, -900]]

In [53]:
# Convert to PyTorch Tensor and set to float
X = torch.tensor(x)
X= X.float()

In [54]:
# Print shape and data type for verification
print(X.shape)
print(X.dtype)

torch.Size([3, 4])
torch.float32


In [55]:
# Compute and display the mean and standard deviation of each column for reference
X.mean(axis = 0)
X.std(axis = 0)

tensor([  4.3589,  20.8167, 404.1452, 404.1452])

In [56]:
X.std(axis = 0)

tensor([  4.3589,  20.8167, 404.1452, 404.1452])

- Your task starts here
- Your normalize_matrix function should take a PyTorch tensor x as input.
- It should return a tensor where the columns are normalized.
- After implementing your function, use the code provided to verify if the mean for each column in Z is close to zero and the standard deviation is 1.

In [57]:
def normalize_matrix(x):
  # Calculate the mean along each column (think carefully , you will take mean along axis = 0 or 1)
  mean = x.mean(axis = 0)

  # Calculate the standard deviation along each column
  std = x.std(axis = 0)

  # Normalize each element in the columns by subtracting the mean and dividing by the standard deviation
  y = (x - mean) /std

  return y  # Return the normalized matrix



In [58]:
Z = normalize_matrix(X)
Z

tensor([[ 0.6882,  0.8006, -1.0722,  1.0722],
        [ 0.4588, -1.1209,  0.1650, -0.1650],
        [-1.1471,  0.3203,  0.9073, -0.9073]])

In [59]:
Z.mean(axis = 0)

tensor([ 0.0000e+00,  4.9671e-08,  3.9736e-08, -3.9736e-08])

# <font color = 'dodgerred'>**Q5: In-place vs. Out-of-place Operations (1 Point)**

1. Create a tensor `A` with values `[1, 2, 3]`.
2. Perform an in-place addition (use `add_` method) of `5` to tensor `A`.
3. Then, create another tensor `B` with values `[4, 5, 6]` and perform an out-of-place addition of `5`.

**Print the memory addresses of `A` and `B` before and after the operations to demonstrate the difference in memory usage. Provide explanation**


In [60]:
A = torch.tensor([1, 2, 3])
print('Original memory address of A:', id(A))
A.add_(5)
print('Memory address of A after in-place addition:', id(A))
print('A after in-place addition:', A)

B = torch.tensor([4, 5, 6])
print('Original memory address of B:', id(B))
B=B+5
print('Memory address of B after out-of-place addition:', id(B))
print('B after out-of-place addition:', B)


Original memory address of A: 134874740532192
Memory address of A after in-place addition: 134874740532192
A after in-place addition: tensor([6, 7, 8])
Original memory address of B: 134874738591920
Memory address of B after out-of-place addition: 134874738591760
B after out-of-place addition: tensor([ 9, 10, 11])


**Provide Explanation for above question here :**


Here, for A, which is an in-place operation. The arithmetic operation is performed in the same location (memory address). It has re-written the initial tensor values with new values.

For B, it is an out-of-place operation, a new copy with the results of the operation is created at a different location. The original location values are still there at the previous location.

Both result in same output, but A is more memory efficient but not used for activities where we are needed to retrieve original values again.

# <font color = 'dodgerred'>**Q6: Tensor Broadcasting (1 Point)**

1. Create two tensors `X` with shape `(3, 1)` and `Y` with shape `(1, 3)`. Perform an addition operation on `X` and `Y`.
2. Explain how broadcasting is applied in this operation by describing the shape changes that occur internally.

In [61]:
X = torch.ones(3,1)
Y = torch.tensor([[1,2,3]])
print('Original shapes:', X.shape, Y.shape)
result = X + Y
print('Result:', result)
print('Result shape:', result.shape)


Original shapes: torch.Size([3, 1]) torch.Size([1, 3])
Result: tensor([[2., 3., 4.],
        [2., 3., 4.],
        [2., 3., 4.]])
Result shape: torch.Size([3, 3])


**Provide Explanation for above question here :**

In broadcasting, smaller-sized tensor is broadcasted to match the dimensions of the larger-sized tensor along the dimensions where they differ so that they have compatible shapes for the arithmetic operation.

X is expanded along the column dimension whose value is 1 to make it as 3*3 matrix and Y is expanded along the row dimension whose value is 1 to make it as 3*3 matrix.

Here, broadcasting was able to happen because each tensor has at least one dimension and starting at the trailing dimension, one of the X, Y dimensions are euqal to 1.


The expanded X is
[1,1,1
1,1,1
1,1,1]

and expanded Y is

[1,2,3
1,2,3
1,2,3]

and they are added.

# <font color = 'dodgerred'>**Q7: Linear Algebra Operations (1 Point)**

1. Create two matrices `M1` and `M2` of compatible shapes for matrix multiplication. Perform the multiplication and print the result.
2. Then, create two vectors `V1` and `V2` and compute their dot product.


In [62]:
M1 = torch.arange(0, 10).reshape(2, 5)
M2 = torch.arange(0, 15).reshape(5, 3)
mat_multiplication = torch.mm(M1,M2)
print('Matrix multiplication result:', mat_multiplication)

V1 = torch.Tensor([1,2,3,4])
V2 = torch.Tensor([3,4,5,6])
dot_product =  torch.dot(V1,V2)
print('Dot product:', dot_product)


Matrix multiplication result: tensor([[ 90, 100, 110],
        [240, 275, 310]])
Dot product: tensor(50.)


# <font color = 'dodgerred'>**Q8: Manipulating Tensor Shapes (1 Point)**

Given a tensor `T` with shape `(2, 3, 4)`, demonstrate how to
1. reshape it to `(3, 8)` using view,
2. reshape it to `(4, 2, 3` using reshape,
3. transpose the first and last dimensions using permute.
4. explain what is the difference between reshape and view

In [63]:
T = torch.rand(2, 3, 4)
T_view =  T.view(3, 8)
print('T_view shape:', T_view.shape)

T_reshape =  T.reshape(4, 2, 3)
print('T_reshape shape:', T_reshape.shape)

T_permute =  T.permute(2,1,0)
print('T_permute shape:', T_permute.shape)

T_view shape: torch.Size([3, 8])
T_reshape shape: torch.Size([4, 2, 3])
T_permute shape: torch.Size([4, 3, 2])


**Provide Explanation for above question here :**

Both view and reshape are used for changing the shape of the tensor without effecting the elements present.

View is like an inplace operation. It does not create a copy and will perform fast and memory efficient computions. It can be operated only on contiguous tensor.

Reshape may or may not share the same memory. Reshape can be performed on both contiguous or non-contiguous tensor.

# <font color = 'dodgerred'>**Q9: Tensor Concatenation and Stacking (1 Point)**

Create tensors `C1` and `C2` both with shape (2, 3).
1. Concatenate them along dimension 0 and then along dimension 1. Print the shape of the resulting tensor.
2. Afterwards, stack the same tensors alomng dimension 0  and print the shape of the resulting tensor.
3. What is the difference between stacking and concatinating.

In [64]:
C1 = torch.rand(2, 3)
C2 = torch.rand(2, 3)
concatenated_dim0 =  torch.cat((C1, C2), dim=0)
print('Concatenated along dimension 0:', concatenated_dim0.shape)

concatenated_dim1 =  torch.cat((C1, C2), dim=1)
print('Concatenated along dimension 1:', concatenated_dim1.shape)

stacked =  torch.stack((C1,C2))
print('Stacked tensor shape:', stacked.shape)


Concatenated along dimension 0: torch.Size([4, 3])
Concatenated along dimension 1: torch.Size([2, 6])
Stacked tensor shape: torch.Size([2, 2, 3])


**Explain the diffrence between concatinating and stacking here**

Concatenation is appending a tensor along a dimension and they become one tensor/matrix. The resulting tensor will have same number of dimensions with varying dimension size (added) in the concatenated dimension.

The tensor must have the same shape except in the concetatenating dimension during concatenation.

Stacking a tensor is appending both tensors as individual tensors. It increases the number of dimensions present.


# <font color = 'dodgerred'>**Q10: Advanced Indexing and Slicing (1 Point)**

1. Given a tensor `D` with shape (6, 6), extract elements that are greater than 0.5.
2. Then, extract the second and fourth rows from `D`.
3. Finally, extract a sub-tensor from the top-left 3x3 block.

In [65]:
D = torch.rand(6, 6)
print('Elements greater than 0.5:\n',  D[D>0.5])

second_fourth_rows =  D[[1,3],:]
print('\nSecond and fourth rows:\n', second_fourth_rows)

top_left_3x3 =  D[0:3,0:3]
print('\nTop-left 3x3 block:\n ', top_left_3x3)


Elements greater than 0.5:
 tensor([0.7104, 0.9464, 0.7890, 0.7886, 0.5895, 0.7539, 0.9103, 0.6440, 0.7071,
        0.6581, 0.8913, 0.5315, 0.6542, 0.6532, 0.9147, 0.9497, 0.6666, 0.9811,
        0.7025])

Second and fourth rows:
 tensor([[0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
        [0.5315, 0.1587, 0.6542, 0.3278, 0.6532, 0.3958]])

Top-left 3x3 block:
  tensor([[0.7104, 0.9464, 0.7890],
        [0.7539, 0.1952, 0.0050],
        [0.6440, 0.7071, 0.6581]])


# <font color = 'dodgerred'>**Q11: Tensor Mathematical Operations (1 Point)**

1. Create a tensor `G` with values from 0 to π in steps of π/4.
2. Compute and print the sine, cosine, and tangent logarithm and the exponential of `G`.

In [66]:
G = torch.tensor([i*torch.pi/4 for i in range(5)])
print('G:', G)
print('Sine of G:',  torch.sin(G))
print('Cosine of G:',  torch.cos(G))
print('Tangent of G:',  torch.tan(G))
print('Natural logarithm of G:',  torch.log(G))
print('Exponential of G:',  torch.exp(G))


G: tensor([0.0000, 0.7854, 1.5708, 2.3562, 3.1416])
Sine of G: tensor([ 0.0000e+00,  7.0711e-01,  1.0000e+00,  7.0711e-01, -8.7423e-08])
Cosine of G: tensor([ 1.0000e+00,  7.0711e-01, -4.3711e-08, -7.0711e-01, -1.0000e+00])
Tangent of G: tensor([ 0.0000e+00,  1.0000e+00, -2.2877e+07, -1.0000e+00,  8.7423e-08])
Natural logarithm of G: tensor([   -inf, -0.2416,  0.4516,  0.8570,  1.1447])
Exponential of G: tensor([ 1.0000,  2.1933,  4.8105, 10.5507, 23.1407])


# <font color = 'dodgerred'>Q12: **Tensor Reduction Operations (1 Point)**

1. Create a 3x2 tensor `H`.
2. Compute the sum of `H`. Print the result and shape after taking sun.
3. Then, perform the same operations along dimension 0 and dimension 1, printing the results and shapes.
4. What do you observe? How the shape changes?

In [67]:
H = torch.rand(3, 2)
print('H:', H, end = "\n\n")
print('Shape of original Tensor H', H.shape, end = "\n\n")

print('Sum of H:',  H.sum())
print('Shape after Sum of H:',  H.sum().shape,  end = "\n\n")

print('Sum of H along dimension 0:',  H.sum(dim=0))
print('Shape after sum of H along dimension 0:', H.sum(dim=0).shape ,  end = "\n\n")

print('Sum of H along dimension 1:', H.sum(dim=1))
print('Shape after sum of H along dimension 1:',  H.sum(dim=1).shape)


H: tensor([[0.6790, 0.9155],
        [0.2418, 0.1591],
        [0.7653, 0.2979]])

Shape of original Tensor H torch.Size([3, 2])

Sum of H: tensor(3.0586)
Shape after Sum of H: torch.Size([])

Sum of H along dimension 0: tensor([1.6861, 1.3725])
Shape after sum of H along dimension 0: torch.Size([2])

Sum of H along dimension 1: tensor([1.5945, 0.4009, 1.0632])
Shape after sum of H along dimension 1: torch.Size([3])


**Provide your observations on shape changes here**

H.sum has returned a scalar value by summing all the elements in the tensor.

dim = 0 is summing along the rows, has resulted in the sum of elements of each column. Hence, dimension is the number of columns.

dim = 1 is summing along the columns, has resulted in the sum of elements of each row. Hence, dimension is the number of rows.


# <font color = 'dodgerred'>**Q13: Working with Tensor Data Types (1 Point)**

1. Create a tensor `I` of data type float with values `[1.0, 2.0, 3.0]`.
2. Convert `I` to data type int and print the result.
3. Explain in which scenarios it's necessary to be cautious about the data type of tensors.

In [68]:
# Solution for Q16
I =  torch.tensor([1.0, 2.0, 3.0])
print('I:', I)
I_int =  I.type(dtype=torch.int)
print('I converted to int:', I_int)

I: tensor([1., 2., 3.])
I converted to int: tensor([1, 2, 3], dtype=torch.int32)


**Your explanations here**

It is necessary to be cautious about the data type of tensors when we want to optimize the memory and in large data cases where memory efficiency is important.

Also, Where precision is important. If we want to round down or compute till the smallest decimal value based on the application area we are working on.


# <font color = 'dodgerred'>**Q14. Speedtest for vectorization 1.5 Points** </font>

Your goal is to measure the speed of linear algebra operations for different levels of vectorization.

1. Construct two matrices $A$ and $B$ with Gaussian random entries of size $1024 \times 1024$.
1. Compute $C = A B$ using matrix-matrix operations and report the time. (Hint: Use torch.mm)
1. Compute $C = A B$, treating $A$ as a matrix but computing the result for each column of $B$ one at a time. Report the time. (hint use torch.mv inside a for loop)
1. Compute $C = A B$, treating $A$ and $B$ as collections of vectors. Report the time. (Hint: use torch.dot inside nested for loop)

In [69]:
## Solution 1
torch.manual_seed(42) # dod not chnage this
A = torch.randn(1024,1024)
B = torch.randn(1024,1024)

In [70]:
## Solution 2
start=time.time()

C = torch.mm(A,B)

print("Matrix by matrix: " + str(time.time()-start) + " seconds")

Matrix by matrix: 0.03574228286743164 seconds


In [71]:
## Solution 3
C= torch.empty(1024,1024)
start = time.time()

for i in range(1024):
  C[:,i]=torch.mv(A,B[:,i])

print("Matrix by vector: " + str(time.time()-start) + " seconds")

Matrix by vector: 0.30179882049560547 seconds


In [72]:
## Solution 4
C= torch.empty(1024,1024)
start = time.time()

for i in range(1024):
  for j in range(1024):
    C[i,j] = torch.dot(A[i],B[:,j])

print("vector by vector: " + str(time.time()-start) + " seconds")

vector by vector: 25.868030309677124 seconds


# <font color = 'dodgerred'>**Q15 : Redo Question 14 by using GPU - 1.5 Points**

<font size = 4, color = 'dodgerred'> **Using GPUs**

How to use GPUs in Google Colab<br>
In Google Colab -- Go to Runtime Tab at top -- select change runtime type -- for hardware accelartor choose GPU

In [73]:
# Check if GPU is availaible
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print(device)

cuda:0


In [74]:
## Solution 1
torch.manual_seed(42)
A= torch.randn((1024, 1024),device=device)
B= torch.randn((1024, 1024),device=device)

In [75]:
## Solution 2
start=time.time()

C = torch.mm(A,B)

print("Matrix by matrix: " + str(time.time()-start) + " seconds")

Matrix by matrix: 0.00033164024353027344 seconds


In [76]:
## Solution 3
C= torch.empty(1024,1024, device = device)
start = time.time()

for i in range(1024):
  C[:,i]=torch.mv(A,B[:,i])

print("Matrix by vector: " + str(time.time()-start) + " seconds")

Matrix by vector: 0.04912614822387695 seconds


In [77]:
## Solution 4
C= torch.empty(1024,1024, device = device)
start = time.time()

for i in range(1024):
  for j in range(1024):
    C[i,j]=torch.dot(A[i,:],B[:,j])

print("vector by vector: " + str(time.time()-start) + " seconds")

vector by vector: 45.2331748008728 seconds
